params:
  dropout: 0.5 
  learning_rate: 0.0001
  batch_normalization: true

  convolution:
    kernel_size:
      DEAP: [32, 40]
    num_kernels: 40

  pooling:
    size: [1, 75]
    stride: 10

  lstm:
    hidden_state_dimension: 64
